# This is a basic workflow to help you get started with Actions

name: New Tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
        
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.6
        with:
          arguments: test
          
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.6
        with:
          arguments: publish -Pversion=${{github.ref_name}} -Pusername=${{github.actor}} -Ppassword=${{github.token}} -PartifactoryUrl=${{secrets.ARTIFACTORY_URL}} -PartifactoryUsername=${{secrets.ARTIFACTORY_USERNAME}} -PartifactoryPassword=${{secrets.ARTIFACTORY_PASSWORD}}